kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: infra3-stella
subjects:
- kind: ServiceAccount
  name: infra3-stella
  namespace: tf-system
roleRef:
  kind: ClusterRole
  name: infra3-stella
  apiGroup: rbac.authorization.k8s.io