apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: infra3-stella
  namespace: tf-system
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/api/v1"
        backend:
          service:
            name: infra3-stella
            port:
              number: 80
