apiVersion: v1
kind: Service
metadata:
  labels:
    service: infra3
    component: api
  name: infra3-stella
  namespace: tf-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5001
  selector:
    service: infra3
    component: api
  type: ClusterIP
